# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: community
name: scaleway
version: 0.0.1
readme: README.md
authors:
  - Ansible (https://github.com/ansible)
  - ndemacon (https://github.com/quantumsheep)
description: Scaleway Ansible Collection.
license_file: LICENSE
tags:
  - scaleway
  - cloud
  - compute
  - instances
repository: https://github.com/ansible-collections/community.scaleway
#documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/ansible-collections/community.scaleway
issues: https://github.com/ansible-collections/community.scaleway/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
  - .DS_Store
  - "*.tar.gz"
